# Generated by Django 5.0.4 on 2024-04-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0002_react_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Anime Title', max_length=256)),
                ('description', models.TextField(default=None, null=True)),
                ('img', models.ImageField(default=None, upload_to='')),
                ('trailer', models.URLField(default=None, null=True)),
                ('status', models.BooleanField(default=False)),
                ('aired_from', models.DateTimeField(auto_now_add=True, null=True)),
                ('aired_to', models.DateTimeField(null=True)),
                ('duration', models.CharField(default=None, max_length=128, null=True)),
                ('episodes', models.IntegerField(default=12, null=True)),
                ('redirect', models.URLField(default=None, null=True)),
                ('broadcast', models.CharField(default=None, max_length=256, null=True)),
                ('rank', models.IntegerField(default=None, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='React',
        ),
    ]
