# Generated by Django 5.0.4 on 2024-04-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0003_anime_delete_react'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='aired_from',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='aired_to',
        ),
        migrations.AddField(
            model_name='anime',
            name='aired',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='rating',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='anime',
            name='studio_name',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='anime',
            name='type',
            field=models.CharField(default='tv', max_length=30),
        ),
        migrations.AlterField(
            model_name='anime',
            name='img',
            field=models.URLField(default=None, null=True),
        ),
    ]
